### ISSUE TITLE
Uncaught ReferenceError: React is not defined

### ISSUE THREAD

**Issue by aequasi** [Merri/react-lazy#1]
Looks like something near the end of the include of the verge stuff is causing the issue. 

Error happens at the VERY end of the dist file

**Comment by Merri** [comment]
The minified file requires React to be exposed in global. Are you adding dist file via require?

**Comment by Marsup** [comment]
Same issue with webpack, I ended up doing `import {Lazy} from 'react-lazy/index.js'`. It's loading the min because package.json's main property is set on it.

**Comment by Merri** [comment]
Took me a bit of time (was sick one week and then too tired the next one) but this issue has now been fixed. Thanks for reporting!
