### ISSUE TITLE
Broken? 

### ISSUE THREAD

**Issue by mherodev** [Merri/react-lazy#10]
Tried the sample inside Create React App:

```jsx
<Lazy
  component="a"
  href="/"
  className="image-link image-link--100px"
  ltIE9
>
  <img
    alt="My Lazy Loaded Image"
    className="image-link__image"
    src="my-lazy-loaded-image.png"
  />
</Lazy>
```

And was met with the following error:

`React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.`

Node v6.11.0
React v15.6.1

Was excited to finally find a lazy-loader that works with horizontal scrolling, but alas. :'(

**Comment by Merri** [comment]
Did you import using `import { Lazy } from 'react-lazy'`? {} are important.

**Comment by mherodev** [comment]
Hah, of course I didn't. Sorry about that. <3
