### ISSUE TITLE
ltIE9 prop

### ISSUE THREAD

**Issue by jooj123** [Merri/react-lazy#16]
First of all - thanks for your work on the lib 
I like it and it seems its the only one that works for all my use cases 🎉 

One thing i did notice is that you have an `ltIE9` prop - is this needed?
React no longer supports ie8 so not sure why this library needs to support it (unnecessary code)

Im happy to throw up a PR for it if you agree

**Comment by Merri** [comment]
Great that it works for you :)

`ltIE9` works by assuming JavaScript won't execute on IE8 and earlier, resulting in rendering the image regardless. The IE conditional comments hide `<noscript />` tags from the browsers so it will simply immediately render the image, or whatever you have inside the component.

The IE specific code doesn't weight all that much, but of course it makes sense to remove it at some point; my current thought would be to remove it by 1.0. Although I don't have a clear road map planned, just some thoughts on what I want to add and some stuff that I need to add (`LazyGroup` needs some further development).
