### ISSUE TITLE
[Question] Would it be possible to specify the cushion in a percent?

### ISSUE THREAD

**Issue by AlexKvazos** [Merri/react-lazy#20]
Would it be possible to specify the cushion in a percent?

Regards

**Comment by Merri** [comment]
Possible, but I don't have a desire to implement it as it feels like it would be a niche feature and possibly adds unnecessary code and complexity. I may consider it if there are others who would like to see it implemented. So far it seems nobody else would be interested to see this.

**Comment by Merri** [comment]
v1.0.0 now supports this.
