### ISSUE TITLE
Too many images are loading

### ISSUE THREAD

**Issue by spenhappenin** [Merri/react-lazy#23]
It works but not based on the viewport. It renders way more images than it should and I am not sure why. I am loading a grid of images and it seems to load like 20 or so before they start to load based on viewport.  Here is the component that I am using it with

`  displayArtWorks = () => {
    return this.props.works.map( work =>
      <Grid.Column key={work.id} mobile={8} tablet={4} computer={4}>
        <Transition visible={this.state.visible} animation='fade' duration={1000}>
          <Link to={`${this.props.path}/${work.id}`} rel="noopener noreferrer">
            <Lazy>
              <Image 
                alt={work.title}
                src={work.src}                
                fluid 
              />
            </Lazy>
          </Link>
        </Transition>
      </Grid.Column>
    )
  }`

Any ideas on how to get around that would be great. Thanks.

**Comment by Merri** [comment]
Have you ensured the elements won't change size before and after an image has started to load? If the size changes upon loading an image then this will cause more elements to be in the viewport compared to the loaded viewport status.

**Comment by Merri** [comment]
v1.0.0 has been released and it probably fixes this issue as it uses IntersectionObserver to detect whether image is in viewport or not. Open new issue if this problem exists with v1.
