### ISSUE TITLE
Image not showing on Chrome v75

### ISSUE THREAD

**Issue by Rawphs** [Merri/react-lazy#27]
Hi, I am having a weird behaviour after this Chrome update, in which _some_ of the images continue to be wrapped in a `<noscript>` and neither `onViewport` and `onLoad` gets called. That is not happening at all with older Chrome versions or different browsers.

Since the code was working fine before this update and that nothing changed on our end and this specific version is the problem, I didn't really know what to share here code-wise.

I'd like to know if you had any issues recently and/or if you have any idea of what could have happened.

**Comment by Merri** [comment]
Hi and thanks for this!

I updated to v75 now and didn't find this issue in my workplace's production site. I did notice though that there is some flickering that I haven't noticed before, but that should be unrelated (I hope).

Which version of React you're running on and is the problem on both production and dev?

**Comment by Rawphs** [comment]
Thank for such fast response!

Both production and dev, I am currently in version 75.0.3770.90. Sometimes everything works just fine, which makes for a very funny ticket filled with comments such as "The issue is gone" and "The issue is back".

What we usually face is that some images load fine and some others are stuck within the `<noscript>`, leading to this:

![image (18)](https://user-images.githubusercontent.com/17144983/59663814-230f7d00-91b0-11e9-967e-82de2a9f206a.png)

I wrote this issue right before going home but I will dig through it today, see if I can find the cause of the problem. I will keep you posted!

**Comment by Rawphs** [comment]
Hey, I had to get other tickets and park this for a while, turns out it was a problem with `overflow: hidden`, it was interfering with the Intersection Observer. I will close this as there is no real issue 😌 

Thank you!
