### ISSUE TITLE
React 15.5: Deprecation warnings for React.createClass and React.PropTypes

### ISSUE THREAD

**Issue by joewestcott** [Merri/react-lazy#7]
Since [react 15.5.0](https://github.com/facebook/react/blob/master/CHANGELOG.md) deprecation warnings are showing in the console for this package:

`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

`Warning: Lazy: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

**Comment by Merri** [comment]
@joewestcott 0.2.0 is rewritten as a ES2015 class :)
